services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: poetry install --no-interaction --no-ansi
    startCommand: poetry run streamlit run app.py --server.port=8000 --server.headless=true
